import { defineConfig } from 'oxlint'

export default defineConfig({
	categories: {
		correctness: 'error',
		suspicious: 'error',
	},
	env: {
		builtin: true,
		browser: true,
		es2024: true,
		node: true,
	},
	rules: {
		'no-irregular-whitespace': 'off',
		'no-underscore-dangle': 'off',
		'accessor-pairs': 'error',
		'array-callback-return': 'error',
		'class-methods-use-this': 'error',
		'curly': ['error', 'all'],
		'default-case-last': 'error',
		'default-param-last': 'error',
		'eqeqeq': 'error',
		'func-name-matching': 'error',
		'grouped-accessor-pairs': 'error',
		'guard-for-in': 'error',
		'init-declarations': 'error',
		'max-classes-per-file': 'error',
		'max-depth': 'error',
		'max-nested-callbacks': 'error',
		'new-cap': 'error',
		'no-array-constructor': 'error',
		'no-bitwise': 'error',
		'no-case-declarations': 'error',
		'no-console': [
			'error',
			{
				allow: ['warn', 'error'],
			},
		],
		'no-constructor-return': 'error',
		'no-div-regex': 'error',
		'no-empty': 'error',
		'no-empty-function': 'error',
		'no-eq-null': 'error',
		'no-extra-label': 'error',
		'no-fallthrough': 'error',
		'no-inner-declarations': 'error',
		'no-label-var': 'error',
		'no-labels': 'error',
		'no-lone-blocks': 'error',
		'no-lonely-if': 'error',
		'no-loop-func': 'error',
		'no-multi-assign': 'error',
		'no-multi-str': 'error',
		'no-negated-condition': 'error',
		'no-nested-ternary': 'error',
		'no-new-func': 'error',
		'no-new-wrappers': 'error',
		'no-object-constructor': 'error',
		'no-param-reassign': 'error',
		'no-proto': 'error',
		'no-prototype-builtins': 'error',
		'no-redeclare': 'error',
		'no-regex-spaces': 'error',
		'no-restricted-globals': 'error',
		'no-restricted-imports': 'error',
		'no-return-assign': 'error',
		'no-script-url': 'error',
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-shadow-restricted-names': [
			'error',
			{
				reportGlobalThis: true,
			},
		],
		'no-template-curly-in-string': 'error',
		'no-throw-literal': 'error',
		'no-useless-call': 'error',
		'no-useless-return': 'error',
		'no-var': 'error',
		'object-shorthand': 'error',
		'operator-assignment': 'error',
		'prefer-const': [
			'error',
			{
				destructuring: 'all',
				ignoreReadBeforeAssign: true,
			},
		],
		'prefer-exponentiation-operator': 'error',
		'prefer-numeric-literals': 'error',
		'prefer-object-spread': 'error',
		'prefer-promise-reject-errors': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'sort-vars': 'error',
		'symbol-description': 'error',
		'unicode-bom': 'error',
		'vars-on-top': 'error',
		'yoda': 'error',
	},
})
