import { defineConfig } from 'oxlint'

export default defineConfig({
	options: {
		typeAware: true,
	},
	env: {
		builtin: true,
	},
	overrides: [
		{
			files: ['**/*.ts', '**/*.vue'],
			rules: {
				'init-declarations': 'off',
				'no-redeclare': 'off',
				'no-undef': 'off',
				'no-array-constructor': 'error',
				'no-unused-expressions': [
					'error',
					{
						allowTernary: true,
					},
				],
				'no-unused-vars': 'off',
				'no-empty-function': 'off',
				'no-throw-literal': 'off',
				'prefer-promise-reject-errors': 'off',
				'require-await': 'off',
				'typescript/ban-ts-comment': 'error',
				'typescript/no-empty-object-type': 'error',
				'typescript/no-explicit-any': 'error',
				'typescript/no-namespace': 'error',
				'typescript/no-require-imports': 'error',
				'typescript/no-unsafe-function-type': 'error',
				'typescript/adjacent-overload-signatures': 'error',
				'typescript/array-type': 'error',
				'typescript/ban-tslint-comment': 'error',
				'typescript/class-literal-property-style': 'error',
				'typescript/consistent-generic-constructors': 'error',
				'typescript/consistent-indexed-object-style': 'error',
				'typescript/consistent-type-assertions': 'error',
				'typescript/consistent-type-definitions': 'error',
				'typescript/no-inferrable-types': 'error',
				'typescript/prefer-for-of': 'error',
				'typescript/prefer-function-type': 'error',
				'typescript/dot-notation': 'error',
				'typescript/non-nullable-type-assertion-style': 'error',
				'typescript/prefer-find': 'error',
				'typescript/prefer-includes': 'error',
				'typescript/prefer-nullish-coalescing': 'off',
				'typescript/prefer-regexp-exec': 'error',
				'typescript/prefer-string-starts-ends-with': 'error',
				'typescript/no-misused-promises': [
					'error',
					{
						checksVoidReturn: false,
					},
				],
				'typescript/no-redundant-type-constituents': 'off',
				'typescript/no-unsafe-argument': 'error',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/only-throw-error': 'error',
				'typescript/prefer-promise-reject-errors': 'error',
				'typescript/require-await': 'error',
				'typescript/restrict-plus-operands': 'error',
				'no-shadow': 'off',
			},
			plugins: ['typescript'],
		},
		{
			files: [
				'**/__tests__/**/*.{js,ts}',
				'**/*.spec.{js,ts}',
				'**/*.test.{js,ts}',
			],
			rules: {
				'typescript/no-explicit-any': 'off',
			},
			plugins: ['typescript'],
		},
	],
	rules: {
		'typescript/consistent-return': 'off',
		'typescript/no-extraneous-class': 'off',
		'typescript/no-meaningless-void-operator': 'off',
		'typescript/no-misused-spread': 'off',
		'typescript/no-unnecessary-boolean-literal-compare': 'off',
		'typescript/no-unnecessary-parameter-property-assignment': 'off',
		'typescript/no-unnecessary-template-expression': 'off',
		'typescript/no-unnecessary-type-arguments': 'off',
		'typescript/no-unnecessary-type-conversion': 'off',
		'typescript/no-unnecessary-type-parameters': 'off',
		'typescript/no-unsafe-type-assertion': 'off',
		'typescript/no-useless-default-assignment': 'off',
		'typescript/no-useless-empty-export': 'off',
		'typescript/require-array-sort-compare': 'off',
	},
})
